package com.sbnz.cep;

import com.sbnz.psychio.model.events.StartExaminationEvent;

global String currentUser;


declare ExaminationLimitEvent
    @role(event)
    @expires(30m)
    username: String
    reason: String
end;



rule "More than 2 examinations in 24h" salience 1
    when
        $e1 : StartExaminationEvent($username : username, username == currentUser)
        Double(this > 2.0) from accumulate(
            $e: StartExaminationEvent(
                username == $username
            ) over window:time( 24h ),
            sum(1.0)
        )
        not (ExaminationLimitEvent(username == $username))
    then
        insert(new ExaminationLimitEvent(currentUser, "More than 2 examination in 24h"));
        System.out.println("EXAMINATION LIMIT EVENT ADDED: " + $username);
end


rule "Examination Limit Handler - 24h" salience 2
    when
        $e1 : StartExaminationEvent($username : username, username == currentUser)
        $e: ExaminationLimitEvent(username == $username)
    then
        System.out.println("\nExamination Limit! User: " + currentUser);
end

