package com.sbnz.rules;

import com.sbnz.psychio.model.Patient;
import com.sbnz.psychio.model.Diagnosis;
import com.sbnz.psychio.model.Examination;
import com.sbnz.psychio.model.DisorderGroup;
import com.sbnz.psychio.model.SymptomFrequency;
import com.sbnz.psychio.model.DisorderGroupSymptomOccurence;
import com.sbnz.psychio.model.DisorderGroupProbability;

import com.sbnz.psychio.model.enums.Severity;
import com.sbnz.psychio.model.enums.Gender;
import com.sbnz.psychio.model.enums.DisorderGroupName;
import com.sbnz.psychio.utility.DateUtility;



rule "test1"
    agenda-group "disorder-group-probability"
    when 
        $e : Examination()
    then
        System.out.println("Examination existsss");
        modify( $e ){ setComment( "Works!" ) } 
end




rule "Classify disorder group - accumulate"
	agenda-group "disorder-group-probability"
	no-loop
	when
	
		$examination : Examination(disorderGroupsDetermined == false, $patientSymptoms: symptoms)
		$disorderGroup : DisorderGroup($symptomOccurences: symptomOccurences)
		
		Double($score: this, this >= $disorderGroup.getMinimumScore()) from accumulate(
        	SymptomFrequency($symptomFrequency : this, $disorderGroup.isSymptomOccurent(symptom)) from $patientSymptoms,
        	sum($symptomFrequency.getFrequency().ordinal() * ((DisorderGroupSymptomOccurence) ($symptomOccurences.get($symptomOccurences.indexOf($symptomFrequency)))).getOccurence())
        )
	then
		System.out.println("DISORDER GROUP CLASSIFY / WITH ACCUMULATE");

		//insert group prediction
		DisorderGroupProbability prob = new DisorderGroupProbability();
		prob.setDisorderGroup($disorderGroup);
		prob.setExamination($examination);
		prob.setProbability($score);

		insert(prob);
		
end




rule "Classify disorder group - without accumulate"
	agenda-group "disorder-group-probability"
	when
		$examination : Examination($patientSymptoms: symptoms)
		$disorderGroup : DisorderGroup($symptomOccurences: symptomOccurences)

	then
		System.out.println("DISORDER GROUP CLASSIFY / NO ACCUMULATE");
		int score = 0;
		for (int i = 0; i < $symptomOccurences.size(); i++) { //FOREACH LOOP DOESN'T WORK IN .DRL FILES
			DisorderGroupSymptomOccurence dgso = (DisorderGroupSymptomOccurence) $symptomOccurences.get(i);
			SymptomFrequency sf = $examination.getSymptomFrequencyIfPresent(dgso.getSymptom());
			if (sf != null){
				score += sf.getFrequency().ordinal()*dgso.getOccurence();
			}
			
		}
		
		if (score > $disorderGroup.getMinimumScore()){
			DisorderGroupProbability prob = new DisorderGroupProbability();
			prob.setDisorderGroup($disorderGroup);
			prob.setExamination($examination);
			prob.setProbability(Double.valueOf(score));

			insert(prob);
		}
				
end

rule "Insert newly created DisorderGroupProbability into Examination"
	no-loop
	agenda-group "disorder-group-probability"
	when 
		$examination : Examination($disorderGroupProbabilities: disorderGroupProbabilities)
		$disorderGroupProbability : DisorderGroupProbability(examination == $examination)
	then
		System.out.println("ADDING DG PROBABILITY TO EXAMINATION");
		$disorderGroupProbabilities.add($disorderGroupProbability);
		update($examination)
		
		
end









