package com.sbnz.rules;

import com.sbnz.psychio.model.Examination;
import com.sbnz.psychio.model.DisorderGroupProbability;
import com.sbnz.psychio.model.enums.DisorderGroupName;


rule "Anorexia rule"
    no-loop
    agenda-group "disorder-group-probability"
	when
	    $e : Examination(bmi < 16, bmi > 0, statementsAnswered == true)
		$disorderGroupProbability : DisorderGroupProbability(examination == $e, disorderGroup.name == DisorderGroupName.EATING_DISORDERS)
	then
		//create diagnosis
		System.out.println("Anorexia predicted");	
end




rule "Bulimia rule"
    no-loop
    agenda-group "disorder-group-probability"
	when
		$e : Examination(bmi >= 16, statementsAnswered == true)
        $disorderGroupProbability : DisorderGroupProbability(examination == $e, disorderGroup.name == DisorderGroupName.EATING_DISORDERS)
	then
		//create diagnosis
		System.out.println("Bulimia predicted");
end


// rule "Non eating disorders"
//     no-loop
//     agenda-group "disorder-group-probability"
//     when
//         $e : Examination($statementResponses : statementResponses, statementsAnswered == true)
//         $disorderGroupProbability : DisorderGroupProbability(examination == $e, disorderGroup.name != DisorderGroupName.EATING_DISORDERS)
//         $

//     then
// end

